### PR TITLE
add  google_analytics

### PR DESCRIPTION
**Pull request by MrBenWang**
add google analytics js code, and this configration code 
but some chrome://extensions/ ( ex :uBlock ) will block this request 

https://support.google.com/analytics/answer/1008080
---
添加谷歌分析的代码，以及相关的配置
但是，会有一些扩展的插件，比如chrome 的 uBlock  插件 会阻止，这种类似的跟踪用户行为的访问。

### CODE REVIEW

**Comment by shaform** [comment]
There was already a version of google analytics https://github.com/xianmin/hugo-theme-jane/blob/b9f2e37fd4ce4351bd3470f74ad524f09bc7bb8b/dev-config.toml#L13

which currently would inject `https://www.google-analytics.com/analytics.js`

**Comment by MrBenWang** [comment]
> googleAnalytics

1. googleAnalytics is different from others ：tencent_analytics，baidu_analytics. So, I think the parameter's position and name are not better.  我认为这个 `googleAnalytics` 参数的名字，和参数的位置，都不太合适，对于其他的`分析`。

https://github.com/xianmin/hugo-theme-jane/blob/b9f2e37fd4ce4351bd3470f74ad524f09bc7bb8b/dev-config.toml#L13

https://github.com/xianmin/hugo-theme-jane/blob/b9f2e37fd4ce4351bd3470f74ad524f09bc7bb8b/dev-config.toml#L149

https://github.com/xianmin/hugo-theme-jane/blob/b9f2e37fd4ce4351bd3470f74ad524f09bc7bb8b/dev-config.toml#L147

2. I can't find the `google_analytics_async.html` file.  我没有在项目中找到这个`google_analytics_async.html`文件。
https://github.com/xianmin/hugo-theme-jane/blob/7f762a3c150d3079410bf1d5f9528b677c2df2bf/layouts/partials/head.html#L106

3. `analytics.js` is obsolete. Google gtag.js is now recommended over analytics.js
https://developers.google.com/analytics/devguides/collection/gtagjs/migration

**Comment by shaform** [comment]
1. googleAnalytics is a built-in feature of hugo, to keep it consistent with other projects, I personally feel that it's better not to create a new config. But maybe this is open to discussion.
2. If `analytics.js` is obsolete, maybe you should report this issue to upstream hugo project.

**Comment by MrBenWang** [comment]
Thx, it’s not necessary.  I did a repetitive thing  😂😂😂

**Pull request closed without merging**
