### PR TITLE
feat: Integrate a Google Custom Search Popup

### PR DESCRIPTION
**Pull request by xianmin**
## Demo 
https://www.xianmin.org/hugo-theme-jane/

deepin-screen-recorder_Select area_20190703222810

## Add option
```toml
  [params.search.google]    # google custom search, see https://cse.google.com
    enable = true
    id = "002186711602136249422:q1gkomof_em"
```

## Reference
https://www.cambiaresearch.com/articles/84/how-to-integrate-a-google-custom-search-popup-in-a-bootstrap-navbar

### CODE REVIEW

**Comment by wzc0x0** [comment]
在我的项目点击没有反应，这段代码竟然没有执行
image

**Comment by xianmin** [comment]
@wzc0x0 Do you have an address for example? It works in [Demo Site](https://www.xianmin.org/hugo-theme-jane/) .

**Comment by wzc0x0** [comment]
https://blog.cankiss.ml

**Comment by xianmin** [comment]
Maybe https://support.google.com/customsearch/answer/4513925?hl=zh-Hans&ctx=topic&visit_id=636987904887075656-111184644&rd=1 , this link could help you.

**Comment by wzc0x0** [comment]
But the search button didn't click? I think is independent of the Google Search

**Comment by shaform** [comment]
I think because the items in `.mobile-menu-item` and `.menu-item` have the same id `openSearch`, only one of them becomes active. In the demo site, the search button does not appear in `.mobile-menu-item`, so the one in `.menu-item` works. However, when the button appear in `.mobile-menu-item`, the one in `.menu-item` no longer works.

**Comment by shaform** [comment]
In addition, it might be better to allow customizing the search dialog title rather than using the fixed `Search Cambia Research`.

**Comment by wzc0x0** [comment]
Yes, when you change page to mobile style, the search button will can click !

**Pull request merged**
