### PR TITLE
Add Wallpaper param (plus other small improvements)

### PR DESCRIPTION
**Pull request by Darthagnon**
It's not perfect yet, but no reason Jane-themed sites should look plain and boring.

chrome_EAp29Z3AKm

Also added wiki as submodule for downloadable documentation.

### CODE REVIEW

**Comment by xianmin** [comment]
Great thanks for your PR! 
I have two suggestions:

1. We don't need docs for wiki for now, it has nothing and I think it should be deprecated... I think if we have more docs we can put them directly to the 'content/' directory in the future.
2. put `wallpaper` config to `full-config.toml` and `dev-config.toml` is better. `config.toml` is a simple config file for new users.

Thanks again!

**Comment by xianmin** [comment]
I have plan to refactor this theme, and add more features, but it depends on my free time...

**Comment by Darthagnon** [comment]
Will implement your suggestions this weekend

**Comment by Darthagnon** [comment]
I can't help wondering - is it worth maintaining 2 config files? Wouldn't just 1 full config with full comments be better? NB. I'm not a professional webdev, so of course defer completely to your preference on your theme; just can't help wondering.

**Comment by Darthagnon** [comment]
@xianmin any more changes you'd like made, or can we get this PR merged?

**Comment by xianmin** [comment]
@Darthagnon Merged. Thank you! 😃

**Pull request merged**
